package com.example.insightku.core.i18n

import androidx.appcompat.app.AppCompatDelegate
import java.util.Locale

/**
 * Domain-layer locale-aware string provider for analytics insight text.
 *
 * Only contains strings generated by [InsightEngine] in the domain layer.
 * UI-only strings (section headers, legends, empty states, etc.) are handled
 * by Android string resources via stringResource().
 *
 * Uses the same locale detection pattern as [NumberFormatter] and [DateFormatter]
 * via [AppCompatDelegate.getApplicationLocales].
 */
object AnalyticsStrings {

    private fun currentLocale(): Locale {
        val locales = AppCompatDelegate.getApplicationLocales()
        return if (!locales.isEmpty) locales[0] ?: Locale.getDefault()
        else Locale.getDefault()
    }

    private fun isIndonesian(): Boolean = currentLocale().language == "id"

    // ══════════════════════════════════════════════════════════════════════════════
    // PERIOD SELECTOR (used by AnalyticsPeriod.kt)
    // ══════════════════════════════════════════════════════════════════════════════

    fun periodWeekly(): String = if (isIndonesian()) "Mingguan" else "Weekly"
    fun periodMonthly(): String = if (isIndonesian()) "Bulanan" else "Monthly"
    fun periodAnnual(): String = if (isIndonesian()) "Tahunan" else "Annual"

    // ══════════════════════════════════════════════════════════════════════════════
    // WEEKLY/MONTHLY NARRATIVE BODIES (complex parameterized, used in UI layer)
    // ══════════════════════════════════════════════════════════════════════════════

    fun weekComparisonBody(
        deltaPercent: Double,
        thisWeekTotal: String,
        lastWeekTotal: String,
        firstWeek: Boolean = false,
        thisWeekAmount: String = ""
    ): String {
        if (isIndonesian()) {
            return if (firstWeek) {
                "Minggu pertama pencatatan — total pengeluaran $thisWeekAmount"
            } else {
                val change = kotlin.math.abs(deltaPercent).toInt()
                if (deltaPercent < 0) {
                    "Anda belanja $change% lebih sedikit dari minggu lalu ($thisWeekTotal vs $lastWeekTotal)"
                } else {
                    "Anda belanja $change% lebih banyak dari minggu lalu ($thisWeekTotal vs $lastWeekTotal)"
                }
            }
        }
        return if (firstWeek) {
            "First week of tracking — $thisWeekAmount total spent"
        } else {
            val change = kotlin.math.abs(deltaPercent).toInt()
            if (deltaPercent < 0) {
                "You spent $change% less than last week ($thisWeekTotal vs $lastWeekTotal)"
            } else {
                "You spent $change% more than last week ($thisWeekTotal vs $lastWeekTotal)"
            }
        }
    }

    fun weeklyHabitBody(
        loudestDay: String,
        loudestAmount: String,
        quietestDay: String,
        quietestAmount: String,
        avgDailySpend: String
    ): String {
        if (isIndonesian()) {
            return "$loudestDay adalah hari pengeluaran terbesar Anda sebesar $loudestAmount, " +
                    "sementara $quietestDay tetap sepi sebesar $quietestAmount. " +
                    "Pengeluaran rata-rata harian: $avgDailySpend."
        }
        return "${loudestDay}s are your biggest spending days at $loudestAmount, " +
                "while ${quietestDay}s stay quiet at $quietestAmount. " +
                "Average daily spend: $avgDailySpend."
    }

    fun cashflowBody(
        earned: String,
        spent: String,
        isPositive: Boolean,
        savingsAmount: String,
        savingsRate: Int
    ): String {
        if (isIndonesian()) {
            return if (isPositive) {
                "Menghasilkan $earned, belanja $spent. Anda menghemat $savingsAmount (tingkat penghematan $savingsRate%)."
            } else {
                "Menghasilkan $earned, belanja $spent. Anda belanja $savingsAmount lebih dari yang Anda hasilkan."
            }
        }
        return if (isPositive) {
            "Earned $earned, spent $spent. You saved $savingsAmount ($savingsRate% savings rate)."
        } else {
            "Earned $earned, spent $spent. You spent $savingsAmount more than you earned."
        }
    }

    // ══════════════════════════════════════════════════════════════════════════════
    // HERO INSIGHTS (generated by InsightEngine in domain layer)
    // ══════════════════════════════════════════════════════════════════════════════

    // Weekly
    fun heroWeekAtGlance(): String = if (isIndonesian()) "Minggu Anda sekilas" else "Your week at a glance"
    fun heroWeekStartLogging(): String = if (isIndonesian()) "Mulai mencatat transaksi untuk melihat wawasan mingguan" else "Start logging transactions to see weekly insights"
    fun heroStayedUnderAvg(days: Int): Pair<String, String> {
        return if (isIndonesian()) {
            "Anda tetap di bawah rata-rata selama $days dari 7 hari" to "Kebiasaan belanja yang konsisten membangun kesehatan keuangan jangka panjang"
        } else {
            "You stayed under your average for $days of 7 days" to "Consistent spending habits build long-term financial health"
        }
    }
    fun heroSpentLessWeek(delta: Int): Pair<String, String> {
        return if (isIndonesian()) {
            "Anda belanja $delta% lebih sedikit dari minggu lalu" to "Kebiasaan belanja Anda bergerak ke arah yang tepat"
        } else {
            "You spent $delta% less than last week" to "Your spending habits are trending in a great direction"
        }
    }
    fun heroSpendingPickedUp(delta: Int): Pair<String, String> {
        return if (isIndonesian()) {
            "Pengeluaran naik $delta% dari minggu lalu" to "Pengeluaran akhir pekan terus mempengaruhi total Anda"
        } else {
            "Spending picked up $delta% from last week" to "Weekend spending continues to influence your total"
        }
    }
    fun heroSteadyWeek(txnCount: Int): Pair<String, String> {
        return if (isIndonesian()) {
            "Minggu stabil dengan $txnCount transaksi" to "Anda mempertahankan ritme belanja yang seimbang"
        } else {
            "Steady week with $txnCount transactions" to "You're maintaining a balanced spending rhythm"
        }
    }

    // Monthly
    fun heroMonthAtGlance(): String = if (isIndonesian()) "Bulan Anda sekilas" else "Your month at a glance"
    fun heroMonthStartLogging(): String = if (isIndonesian()) "Mulai mencatat transaksi untuk melihat wawasan kesehatan keuangan" else "Start logging transactions to see financial health insights"
    fun heroSavedPctIncome(pct: Int): Pair<String, String> {
        return if (isIndonesian()) {
            "Anda menghemat $pct% dari pemasukan bulan ini" to "Ini adalah bulan penghematan paling konsisten Anda"
        } else {
            "You saved $pct% of your income this month" to "This was your most consistent saving month"
        }
    }
    fun heroPositiveBalance(): Pair<String, String> {
        return if (isIndonesian()) {
            "Saldo positif bulan ini" to "Anda menghasilkan lebih dari yang dibelanjakan — pertahankan"
        } else {
            "Positive balance this month" to "You earned more than you spent — keep it up"
        }
    }
    fun heroExpensesDroppedMonth(delta: Int): Pair<String, String> {
        return if (isIndonesian()) {
            "Pengeluaran turun $delta% dari bulan lalu" to "Disiplin pengeluaran Anda meningkat"
        } else {
            "Expenses dropped $delta% from last month" to "Your spending discipline is improving"
        }
    }
    fun heroSpendingRoseMonth(delta: Int): Pair<String, String> {
        return if (isIndonesian()) {
            "Pengeluaran naik $delta% dari bulan lalu" to "Luangkan waktu untuk meninjau ke mana uang Anda pergi"
        } else {
            "Spending rose $delta% from last month" to "Take a moment to review where it went"
        }
    }
    fun heroSteadyMonth(txnCount: Int): Pair<String, String> {
        return if (isIndonesian()) {
            "Bulan stabil dengan $txnCount transaksi" to "Keuangan Anda tetap seimbang"
        } else {
            "Steady month with $txnCount transactions" to "Your finances are staying balanced"
        }
    }

    // Annual
    fun heroYearAtGlance(): String = if (isIndonesian()) "Tahun Anda sekilas" else "Your year in review"
    fun heroYearStartLogging(): String = if (isIndonesian()) "Mulai mencatat transaksi untuk melihat perjalanan keuangan Anda" else "Start logging transactions to see your financial journey"
    fun heroExpensesDroppedYear(delta: Int): Pair<String, String> {
        return if (isIndonesian()) {
            "Pengeluaran turun $delta% dari tahun lalu" to "Ini adalah tahun keuangan terkuat Anda sejauh ini"
        } else {
            "Expenses dropped $delta% from last year" to "This has been your strongest financial year so far"
        }
    }
    fun heroSavedPctTotal(pct: Int): Pair<String, String> {
        return if (isIndonesian()) {
            "Anda menghemat $pct% dari total pemasukan tahun ini" to "Disiplin keuangan Anda membuahkan hasil"
        } else {
            "You saved $pct% of your total income" to "Your financial discipline is paying off"
        }
    }
    fun heroBestMonth(monthLabel: String, saved: String): Pair<String, String> {
        return if (isIndonesian()) {
            "$monthLabel adalah bulan terbaik Anda" to "Anda menghemat $saved bulan itu"
        } else {
            "$monthLabel was your best month" to "You saved $saved that month"
        }
    }
    fun heroYearTracked(months: Int): Pair<String, String> {
        return if (isIndonesian()) {
            "Tahun dengan $months bulan tercatat" to "Cerita keuangan Anda mulai terbentuk"
        } else {
            "A year of $months months tracked" to "Your financial story is taking shape"
        }
    }

    // ══════════════════════════════════════════════════════════════════════════════
    // INSIGHT ENGINE TEXT (generated by InsightEngine in domain layer)
    // ══════════════════════════════════════════════════════════════════════════════

    // Personality
    fun personalityWeekend(): String = if (isIndonesian()) "Akhir pekan adalah tempat uang Anda paling keras" else "Weekends are where your money goes loud"
    fun personalityWeekday(): String = if (isIndonesian()) "Anda belanja dalam burst fokus selama seminggu" else "You spend in focused bursts during the week"
    fun personalitySteady(): String = if (isIndonesian()) "Anda menjaga ritme yang stabil dan mudah dengan uang Anda" else "You keep a steady, easy rhythm with your money"
    fun personalityOnboarding(): String = if (isIndonesian()) "Terus mencatat — wawasan muncul setelah beberapa transaksi" else "Keep logging — insights appear after a few transactions"

    // Two Yous
    fun twoYousDiverge(): String = if (isIndonesian()) "Akhir Pekan Anda dan Hari Kerja Anda pada dasarnya dua orang berbeda." else "Weekend You and Weekday You are basically two different people."
    fun twoYousSame(): String = if (isIndonesian()) "Ternyata Anda hampir sama sepanjang minggu." else "Turns out you're pretty much the same person all week."
    fun twoYousGap(): String = if (isIndonesian()) "Ada kesenjangan antara pengeluaran hari kerja dan akhir pekan Anda." else "There's a gap between your weekday and weekend spending."

    // Patterns
    fun patternWeekendSpending(): String = if (isIndonesian()) "Sekitar setengah pengeluaran Anda terjadi di akhir pekan." else "About half your spending lands on weekends."
    fun patternRegularCategory(category: String, days: Int): String {
        if (isIndonesian()) return "$category sudah menjadi langganan — muncul di $days hari berbeda."
        return "$category has been a regular — it showed up on $days different days."
    }
    fun patternAboveAvgDays(count: Int): String {
        if (isIndonesian()) return "$count hari memiliki pengeluaran 50% di atas rata-rata harian Anda."
        return "$count days had spending 50% above your daily average."
    }

    // Noticing
    fun noticingNightOwl(): String = if (isIndonesian()) "Sebagian besar pengeluaran Anda terjadi di akhir pekan — hari libur bertambah lebih dari yang terasa." else "A good slice of your spending happens on weekends — the days off add up more than they feel like."

    // Mood
    fun moodCalm(): String = if (isIndonesian()) "Lebih tenang belakangan ini" else "Calmer lately"
    fun moodSteady(): String = if (isIndonesian()) "Tetap stabil" else "Staying steady"
    fun moodRestless(): String = if (isIndonesian()) "Sedikit gelisah" else "A little restless"

    // Rhythm
    fun rhythmLoudest(dayName: String): String {
        if (isIndonesian()) return "$dayName adalah hari pengeluaran paling keras Anda"
        return "${dayName}s are your loudest spending days"
    }

    // ══════════════════════════════════════════════════════════════════════════════
    // ANALYTICS LABELS (from spec, for future use across the app)
    // ══════════════════════════════════════════════════════════════════════════════

    fun labelIncome(): String = if (isIndonesian()) "Pemasukan" else "Income"
    fun labelExpense(): String = if (isIndonesian()) "Pengeluaran" else "Expense"
    fun labelSavings(): String = if (isIndonesian()) "Tabungan" else "Savings"
    fun labelBalance(): String = if (isIndonesian()) "Saldo" else "Balance"
    fun labelCashFlow(): String = if (isIndonesian()) "Arus Kas" else "Cash Flow"
    fun labelBudget(): String = if (isIndonesian()) "Anggaran" else "Budget"
    fun labelGoal(): String = if (isIndonesian()) "Tujuan" else "Goal"
    fun labelRecurring(): String = if (isIndonesian()) "Berulang" else "Recurring"
    fun labelInstallment(): String = if (isIndonesian()) "Cicilan" else "Installment"
    fun labelAllocation(): String = if (isIndonesian()) "Alokasi" else "Allocation"
    fun labelAverage(): String = if (isIndonesian()) "Rata-rata" else "Average"
    fun labelMaximum(): String = if (isIndonesian()) "Maksimum" else "Maximum"
    fun labelMinimum(): String = if (isIndonesian()) "Minimum" else "Minimum"
    fun labelHighest(): String = if (isIndonesian()) "Tertinggi" else "Highest"
    fun labelLowest(): String = if (isIndonesian()) "Terendah" else "Lowest"
    fun labelDaily(): String = if (isIndonesian()) "Harian" else "Daily"
    fun labelWeekly(): String = if (isIndonesian()) "Mingguan" else "Weekly"
    fun labelMonthly(): String = if (isIndonesian()) "Bulanan" else "Monthly"
    fun labelYearly(): String = if (isIndonesian()) "Tahunan" else "Yearly"
}
